site_name: Contributor Documentation
site_url: https://papermoonio.github.io/papermoon-mkdocs
docs_dir: papermoon-docs
copyright: © 2025
theme: 
  name: material
  custom_dir: material-overrides
  favicon: assets/images/favicon.webp
  logo: assets/images/papermoon.webp
  icon: 
    admonition: # Assigns icons per custom admonition type
      code: material/code-tags
  palette:
    primary: custom
  font: 
    text: Sora
  features:
    - content.code.annotate # Adds annotations to code blocks
    - content.code.copy # Adds copy to clipboard button to code snippets
    - content.tooltips # Adds tooltips
    - navigation.footer # Shows previous and next on the footer
    - navigation.tabs # Top-level sections are rendered below the header (can be modified to in-line with CSS)
    - navigation.tabs.sticky # When scrolling, the tabs remain at the top of the page
    - navigation.sections # Render top-level sections as groups in the sidebar
    - navigation.indexes # Index pages
    - navigation.top # Show the back to top button since we don't keep top nav sticky
    - content.action.edit
extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: True
      line_spans: __span
      pygments_lang_class: True
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: papermoon-docs/.snippets
      url_download: True
      dedent_subsections: True
  - pymdownx.tabbed:
      alternate_style: True
  - toc:
      title: ' '
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        # Redirects will go here as pages get moved around in the following format:
        # old-page.md: new-page.md
  - macros:
      include_yaml:
        - papermoon-docs/variables.yml
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      exclude:
        - node_modules/*
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]